# docker-compose.yml

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - guess-the-rating-network

  backend:
    build: ./backend
    command: gunicorn guess_the_rating.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G
    networks:
      - guess-the-rating-network
    environment:
      - ALLOWED_HOSTS=localhost 127.0.0.1 backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/src/framer
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://backend:8000
      - NODE_OPTIONS=--max-old-space-size=8192
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G
    networks:
      - guess-the-rating-network
    ports:
      - "3000:3000"


networks:
  guess-the-rating-network:
    driver: bridge

volumes:
  postgres_data:

